# SERVER CONFIGURATIONS
http:
  host: localhost
  port: 8080
  # this is not necessary,
  # we were recommended against
  # using default srv parameters
  read_timeout: 10s
  write_timeout: 30s
  idle_timeout: 60s

# DATABASE CREDENTIALS
postgres:
  host: localhost
  port: 5432
  user_name: postgres
  password: postgres
  db_name: postgres
  driver_name: postgres

# API
api:
  user:
    mandatory_params:
      - Fullname
      - Email
      - Password
    endpoint: /users