# SERVER CONFIGURATIONS
http:
  host: localhost
  port: 8080
  # this is not necessary,
  # we were recommended against
  # using default server parameters
  readTimeout: 10s
  writeTimeout: 30s
  idleTimeout: 60s

# DATABASE CREDENTIALS
postgres:
  host: localhost
  port: 5432
  user_name: postgres
  password: postgres
  db_name: postgres
  driver_name: pgx

# API
api:
  user:
    mandatory_params:
      - Fullname
      - Email
      - Password
    endpoint: /users