openapi: 3.0.0
info:
  title: Heroes
  description: Made by Super Puper Heroes
  version: 0.0.0
servers:
  - url: 'http://localhost:8080'
    description: Local development

#https://swagger.io/docs/specification/basic-structure/

paths:
  /users:
    post:
      summary: Create a user, returns an object
      operationId: createUser
      requestBody:
        description: user to add
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        201:
          description: User created response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: uint
          minLength: 36
          maxLength: 36
        fullname:
          type: string
          required: true
          minLength: 3
          maxLength: 256
        email:
          type: string
          required: true
          uniqueItems: true
        password:
          type: string
          required: true
          minLength: 8
          maxLength: 256
        createdAt:
          type: string
          format: "date-time"

